on:
  push:
    branches:
      - main
    tags:
      - 'v*'
name: Build docker image
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker Image
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/blockdaemon/solana-cluster-manager
          tags: |
            type=sha,event=branch,prefix=
            type=raw,value=latest
            type=ref,event=tag

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: GITHUB_SHA=${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
